### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by the4ndy** [qarmin/Instrukcje-i-Tutoriale#15]
**ERROR**
```
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
Unsupported config option for services.deemix-config-data: 'name'
Unsupported config option for services.deemix-data: 'name'
```

**CONFIG**
```
version: '3.7'

services:
  deemix:
    container_name: deemix
    image: bocki/deemix
    restart: unless-stopped
    ports:
      - 9666:9666
    environment:
      - PUID=1000
      - PGID=1000
      - ARL=REDACTED
    volumes:
      - /home/sheriff/deezer:/downloads
      - deemix-config-data:/config


  deemix-data:
    name: deemix-data
  deemix-config-data:
    name: deemix-config-data
```

**Comment by the4ndy** [comment]
**Steps**

- follow instructions from Readme (I am using Windows with Docker Desktop, on that note, docker isnt supported in WSL, so that mention is probably misleading)
- copy and paste config file, change only the ARL and the path BEFORE the colon under volumes
- save and run ```docker-compose up -d```
- it gives the error in the comment above

**Comment by qarmin** [comment]
Should be fixed with - https://github.com/qarmin/Instrukcje-i-Tutoriale/commit/99ac15b9c05d5770bb4feef03e59d5dc5b30170a
Thanks for the report.
